#!/bin/sh -e

if [ "$1" = configure ]
then
    lnk=[[pkg.prefix]]/[[pkg.configdir]]
    dst=/etc/[[name]]
    if [ ! -L $lnk ] && [ -d $dst ]; then
        ln -s $dst $lnk 
    fi
    lnk=[[pkg.prefix]]/public/.htaccess
    dst=/etc/[[name]]/htaccess
    if [ ! -L $lnk ] && [ -f $dst ]; then
        ln -s $dst $lnk 
    fi
fi

exit 0
